# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       nemo-qml-plugins

# >> macros
# << macros

Summary:    Nemo QML plugins source package.
Version:    0.3.5
Release:    1
Group:      System/Libraries
License:    BSD
URL:        https://github.com/nemomobile/nemo-qml-plugins
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-qml-plugins.yaml
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(QtContacts)
BuildRequires:  pkgconfig(QtWebKit)
BuildRequires:  pkgconfig(mlite)
BuildRequires:  pkgconfig(libsignon-qt)
BuildRequires:  pkgconfig(accounts-qt) >= 1.4
BuildRequires:  pkgconfig(timed)
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(QtSparql)

%description
Do not install this, install the subpackaged plugins.

%package contacts
Summary:    QML contacts plugin
Group:      System/Libraries

%description contacts
A more performant (and less problematic) QtContacts QML binding

%package contacts-tests
Summary:    QML contacts plugin tests
Group:      System/Libraries

%description contacts-tests
Tests for QML contacts plugin

%package messages
Summary:    Plugin providing public messages API
Group:      System/Libraries

%description messages
Plugin providing public API for interacting with messages applications

%package accounts
Summary:    Accounts framework support for QML applications
Group:      System/Libraries

%description accounts
Plugin providing libaccounts framework support for QML applications

%package accounts-tests
Summary:    QML accounts plugin tests
Group:      System/Libraries

%description accounts-tests
Tests for QML accounts plugin

%package signon
Summary:    Signon framework support for QML applications
Group:      System/Libraries

%description signon
Plugin providing libsignon framework support for QML applications

%package signon-tests
Summary:    QML signon plugin tests
Group:      System/Libraries

%description signon-tests
Tests for QML signon plugin

%package utilities
Summary:    Miscellaneous utility elements for QML applications
Group:      System/Libraries

%description utilities
Miscellaneous utility elements for QML applications.

%package notifications
Summary:    Notification support for QML applications
Group:      System/Libraries

%description notifications
Plugin providing notification support for QML applications

%package notifications-devel
Summary:    Notification support for C++ applications
Group:      System/Libraries

%description notifications-devel
Library providing notification support for C++ applications


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post


%files contacts
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/contacts/libnemocontacts.so
%{_libdir}/qt4/imports/org/nemomobile/contacts/qmldir
# >> files contacts
# << files contacts

%files contacts-tests
%defattr(-,root,root,-)
/opt/tests/nemo-qml-plugins/contacts/*
# >> files contacts-tests
# << files contacts-tests

%files messages
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/messages/libnemomessages.so
%{_libdir}/qt4/imports/org/nemomobile/messages/qmldir
# >> files messages
# << files messages

%files accounts
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/accounts/libnemoaccounts.so
%{_libdir}/qt4/imports/org/nemomobile/accounts/qmldir
# >> files accounts
# << files accounts

%files accounts-tests
%defattr(-,root,root,-)
/opt/tests/nemo-qml-plugins/accounts/*
%{_datadir}/accounts/providers/test-provider.provider
%{_datadir}/accounts/services/test-service2.service
%{_datadir}/accounts/service_types/test-service-type2.service-type
# >> files accounts-tests
# << files accounts-tests

%files signon
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/signon/libnemosignon.so
%{_libdir}/qt4/imports/org/nemomobile/signon/qmldir
# >> files signon
# << files signon

%files signon-tests
%defattr(-,root,root,-)
/opt/tests/nemo-qml-plugins/signon/*
# >> files signon-tests
# << files signon-tests

%files utilities
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/utilities/libnemoutilities.so
%{_libdir}/qt4/imports/org/nemomobile/utilities/qmldir
# >> files utilities
# << files utilities

%files notifications
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/notifications/libnemonotifications.so
%{_libdir}/qt4/imports/org/nemomobile/notifications/qmldir
# >> files notifications
# << files notifications

%files notifications-devel
%defattr(-,root,root,-)
%{_includedir}/nemo-qml-plugins/notifications/*.h
%{_libdir}/pkgconfig/nemonotifications.pc
# >> files notifications-devel
# << files notifications-devel
