# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       nemo-qml-plugins

# >> macros
# << macros

Summary:    Nemo QML plugins source package.
Version:    0.3.5
Release:    1
Group:      System/Libraries
License:    BSD
URL:        https://github.com/nemomobile/nemo-qml-plugins
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-qml-plugins.yaml
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(mlite)

%description
Do not install this, install the subpackaged plugins.

%package messages
Summary:    Plugin providing public messages API
Group:      System/Libraries

%description messages
Plugin providing public API for interacting with messages applications

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post


%files messages
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/messages/libnemomessages.so
%{_libdir}/qt4/imports/org/nemomobile/messages/qmldir
# >> files messages
# << files messages
