# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       nemo-qml-plugins

# >> macros
# << macros

Summary:    Nemo QML plugins source package.
Version:    0.1.7
Release:    1
Group:      System/Libraries
License:    BSD
URL:        https://github.com/nemomobile/nemo-qml-plugins
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-qml-plugins.yaml
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(QtContacts)
BuildRequires:  pkgconfig(QtWebKit)
BuildRequires:  pkgconfig(qmfclient)
BuildRequires:  pkgconfig(mlite)
BuildRequires:  pkgconfig(accounts-qt)
BuildRequires:  pkgconfig(libsignon-qt)

%description
Do not install this, install the subpackaged plugins.

%package thumbnailer
Summary:    QML thumbnail service plugin
Group:      System/Libraries

%description thumbnailer
QML plugin for accessing a shared thumbnail cache and fast image thumbnailing.

%package contacts
Summary:    QML contacts plugin
Group:      System/Libraries

%description contacts
A more performant (and less problematic) QtContacts QML binding

%package contacts-tests
Summary:    QML contacts plugin tests
Group:      System/Libraries

%description contacts-tests
Tests for QML contacts plugin

%package qrencode
Summary:    QR encoder plugin
Group:      System/Libraries

%description qrencode
A QML QR encoder plugin

%package folderlistmodel
Summary:    Folder list model for QML applications
Group:      System/Libraries

%description folderlistmodel
A model providing a view of the filesystem for QML applications

%package configuration
Summary:    Persistant configuration plugin for QML applications
Group:      System/Libraries

%description configuration
A plugin providing persistent configuration for QML applications

%package email
Summary:    Plugin providing email via Qt Messaging Framework (QMF) backend
Group:      System/Libraries

%description email
Plugin providing email via Qt Messaging Framework (QMF) backend.

%package messages
Summary:    Plugin providing messaging via telepathy
Group:      System/Libraries

%description messages
Plugin providing messaging via telepathy backend.

%package accounts
Summary:    Plugin providing accounts functionality via libaccounts-qt
Group:      System/Libraries

%description accounts
Plugin providing accounts functionality via libaccounts-qt

%package accounts-tests
Summary:    QML accounts plugin tests
Group:      System/Libraries

%description accounts-tests
Tests for QML accounts plugin

%package signon
Summary:    Plugin providing signon functionality via libsignon-qt
Group:      System/Libraries

%description signon
Plugin providing signon functionality via libsignon-qt

%package signon-tests
Summary:    QML signon plugin tests
Group:      System/Libraries

%description signon-tests
Tests for QML signon plugin

%prep
%setup -q -n %{name}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post


%files thumbnailer
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/thumbnailer/libnemothumbnailer.so
%{_libdir}/qt4/imports/org/nemomobile/thumbnailer/thumbnailers/libvideothumbnailer.so
%{_libdir}/qt4/imports/org/nemomobile/thumbnailer/qmldir
# >> files thumbnailer
# << files thumbnailer

%files contacts
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/contacts/libnemocontacts.so
%{_libdir}/qt4/imports/org/nemomobile/contacts/qmldir
# >> files contacts
# << files contacts

%files contacts-tests
%defattr(-,root,root,-)
/opt/tests/nemo-qml-plugins/contacts/*
# >> files contacts-tests
# << files contacts-tests

%files qrencode
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/qrencode/libqrencoder.so
# >> files qrencode
# << files qrencode

%files folderlistmodel
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/folderlistmodel/libnemofolderlistmodel.so
%{_libdir}/qt4/imports/org/nemomobile/folderlistmodel/qmldir
# >> files folderlistmodel
# << files folderlistmodel

%files configuration
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/configuration/libnemoconfiguration.so
%{_libdir}/qt4/imports/org/nemomobile/configuration/qmldir
# >> files configuration
# << files configuration

%files email
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/email/libnemoemail.so
%{_libdir}/qt4/imports/org/nemomobile/email/qmldir
# >> files email
# << files email

%files messages
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/messages/libnemomessages.so
%{_libdir}/qt4/imports/org/nemomobile/messages/qmldir
# >> files messages
# << files messages

%files accounts
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/accounts/libnemoaccounts.so
%{_libdir}/qt4/imports/org/nemomobile/accounts/qmldir
# >> files messages
# << files messages

%files accounts-tests
%defattr(-,root,root,-)
/opt/tests/nemo-qml-plugins/accounts/*
/usr/share/accounts/providers/test-provider.provider
/usr/share/accounts/services/test-service.service
# >> files accounts-tests
# << files accounts-tests

%files signon
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/signon/libnemosignon.so
%{_libdir}/qt4/imports/org/nemomobile/signon/qmldir
# >> files messages
# << files messages

%files signon-tests
%defattr(-,root,root,-)
/opt/tests/nemo-qml-plugins/signon/*
# >> files signon-tests
# << files signon-tests
